from .division import *
from .doctor import *
from .employee import *
from .place import *
from .position import *
from .privilage import *
from .product import *
from .role import *
from .room import *
