"""add picture_url to product

Revision ID: 915d27de520b
Revises: 87e34954be29
Create Date: 2023-11-16 00:41:24.759381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "915d27de520b"
down_revision: Union[str, None] = "87e34954be29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("picture_url", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "picture_url")
    # ### end Alembic commands ###
