"""bytea pass hash

Revision ID: 71bf33f1c8b6
Revises: 720ad8b4711a
Create Date: 2023-12-23 15:50:15.119343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "71bf33f1c8b6"
down_revision: Union[str, None] = "720ad8b4711a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password_hash",
        existing_type=sa.TEXT(),
        type_=postgresql.BYTEA(),
        existing_nullable=False,
        postgresql_using="password_hash::bytea",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password_hash",
        existing_type=postgresql.BYTEA(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
